// eslint-disable-next-line no-unused-vars
import React from 'react';

const imageLinks = [{
  'Atlanta Hawks': <a href="https://imgur.com/dVOYa1d"><img src="https://i.imgur.com/dVOYa1d.png" title="source: imgur.com" /></a>,
  'Boston Celtics': <a href="https://imgur.com/eSXRefZ" > <img src="https://i.imgur.com/eSXRefZ.png" title="source: imgur.com" /></a>,
  'Brooklyn Nets': <a href="https://imgur.com/XMdohJg"><img src="https://i.imgur.com/XMdohJg.png" title="source: imgur.com" /></a>,
  'Charlotte Hornets': < a href = "https://imgur.com/sdyAefA" > <img src="https://i.imgur.com/sdyAefA.png" title="source: imgur.com" /></a>,
  'Chicago Bulls': <a href="https://imgur.com/VkJWahl"><img src="https://i.imgur.com/VkJWahl.png" title="source: imgur.com" /></a>,
  'Cleveland Cavaliers': <a href="https://imgur.com/1SQFjkp" > <img src="https://i.imgur.com/1SQFjkp.png" title="source: imgur.com" /></a>,
  'Dallas Mavericks': <a href="https://imgur.com/ZIKdAK8"><img src="https://i.imgur.com/ZIKdAK8.png" title="source: imgur.com" /></a>,
  'Denver Nuggets': < a href = "https://imgur.com/ADmVfDV" > <img src="https://i.imgur.com/ADmVfDV.png" title="source: imgur.com" /></a>,
  'Detroit Pistons': <a href="https://imgur.com/r6AzUcs"><img src="https://i.imgur.com/r6AzUcs.png" title="source: imgur.com" /></a>,
  'Golden State Warriors': <a href="https://imgur.com/ahEVGDX"><img src="https://i.imgur.com/ahEVGDX.png" title="source: imgur.com" /></a>,
  'Houston Rockets': <a href="https://imgur.com/Z80BEZD"><img src="https://i.imgur.com/Z80BEZD.png" title="source: imgur.com" /></a>,
  'Indiana Pacers': <a href="https://imgur.com/K9AvzPA"><img src="https://i.imgur.com/K9AvzPA.png" title="source: imgur.com" /></a>,
  'LA Clippers': <a href="https://imgur.com/fLXtlz9"><img src="https://i.imgur.com/fLXtlz9.png" title="source: imgur.com" /></a>,
  'Los Angeles Lakers': < a href="https://imgur.com/FZHFMp3" > <img src="https://i.imgur.com/FZHFMp3.png" title="source: imgur.com" /></a>,
  'Memphis Grizzlies': <a href="https://imgur.com/v2wAUlK"><img src="https://i.imgur.com/v2wAUlK.png" title="source: imgur.com" /></a>,
  'Miami Heat': <a href="https://imgur.com/uO7qMiT"><img src="https://i.imgur.com/uO7qMiT.png" title="source: imgur.com" /></a>,
  'Milwaukee Bucks': <a href="https://imgur.com/wqHhd1h"><img src="https://i.imgur.com/wqHhd1h.png" title="source: imgur.com" /></a>,
  'Minnesota Timberwolves': <a href="https://imgur.com/3eOUK3x"><img src="https://i.imgur.com/3eOUK3x.png" title="source: imgur.com" /></a>,
  'New Orleans Pelicans': <a href="https://imgur.com/99sUMgQ"><img src="https://i.imgur.com/99sUMgQ.png" title="source: imgur.com" /></a>,
  'New York Knicks': <a href="https://imgur.com/FXPOBR6"><img src="https://i.imgur.com/FXPOBR6.png" title="source: imgur.com" /></a>,
  'Oklahoma City Thunder': <a href="https://imgur.com/MyMQHCN"><img src="https://i.imgur.com/MyMQHCN.png" title="source: imgur.com" /></a>,
  'Orlando Magic': <a href="https://imgur.com/7jkkqEK"><img src="https://i.imgur.com/7jkkqEK.png" title="source: imgur.com" /></a>,
  'Philadelphia 76ers': <a href="https://imgur.com/QNULjIC"><img src="https://i.imgur.com/QNULjIC.png" title="source: imgur.com" /></a>,
  'Phoenix Suns': <a href="https://imgur.com/1YrZuiC"><img src="https://i.imgur.com/1YrZuiC.png" title="source: imgur.com" /></a>,
  'Portland Trail Blazers': <a href="https://imgur.com/qg2YCWG"><img src="https://i.imgur.com/qg2YCWG.png" title="source: imgur.com" /></a>,
  'Sacramento Kings': <a href="https://imgur.com/YV79rfC"><img src="https://i.imgur.com/YV79rfC.png" title="source: imgur.com" /></a>,
  'San Antonio Spurs': <a href="https://imgur.com/2NovGpG"><img src="https://i.imgur.com/2NovGpG.png" title="source: imgur.com" /></a>,
  'Toronto Raptors': <a href="https://imgur.com/lhpoaTx"><img src="https://i.imgur.com/lhpoaTx.png" title="source: imgur.com" /></a>,
  'Washington Wizards': <a href="https://imgur.com/DE5fgQ7"><img src="https://i.imgur.com/DE5fgQ7.png" title="source: imgur.com" /></a>,
}];
export default imageLinks;
